# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: true
font: ''
font_size: M

# SEO

site_type: 'Organization'
local_business_type: ''
org_name: ''
description: 'PolyU Edge Intelligence Lab'
twitter: ''

# Contact (edit or remove options as required)

# email: test@example.org
# phone: 888 888 88 88
# address:
#   street: Mong Man Wai Building, Department of Computing, The Hong Kong Polytechnic University
#   city: Hung Hom, Kowloon, Hong Kong SAR
#   region: CA
#   postcode: '94305'
#   country: United States
#   country_code: US
coordinates:
  latitude: '22.304194857359292'
  longitude: '114.18058002713065'
directions: Mong Man Wai Building, Department of Computing, The Hong Kong Polytechnic University, Hung Hom, Kowloon, Hong Kong SAR
# office_hours:
#   - 'Monday 10:00 to 13:00'
#   - 'Wednesday 09:00 to 10:00'
# appointment_url: 'https://calendly.com'
# contact_links:
#   - icon: twitter
#     icon_pack: fab
#     name: DM Me
#     link: 'https://twitter.com/Twitter'
#   - icon: skype
#     icon_pack: fab
#     name: Skype Me
#     link: 'skype:echo123?call'
#   - icon: keybase
#     icon_pack: fab
#     name: Chat on Keybase
#     link: 'https://keybase.io/'
#   - icon: comments
#     icon_pack: fas
#     name: Discuss on Forum
#     link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: false
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
highlight_languages:
  - r
  - python
  - latex
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: false
  page: false
  post: false
  project: false
  publication: false
  event: false
reading_time: true
section_pager: false
docs_section_pager: false
sharing: false
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: false
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: square
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: false
comments:
  provider: ''
  commentable:
    post: false
    book: false
    project: false
    publication: false
    event: false
  disqus:
    shortname: ''
    show_count: false
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
